name: Pip.Services Entities microservice in Node.JS

on: 
  push:
    paths:
    - '**'
    - '!README.md'

jobs:
  Default:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - uses: actions/checkout@main
    
    #### Set excecution premission ####
    - name : set chmod
      run: |
        chmod u+x ./clean.ps1
        chmod u+x ./build.ps1
        chmod u+x ./test.ps1
        chmod u+x ./tag.ps1
        chmod u+x ./run.ps1
        chmod u+x ./package.ps1
        chmod u+x ./release.ps1
        chmod u+x ./publish.ps1
        
  
    ############# Prepare #############

    - name: Install prereq and save build number
      id: build_info
      uses: pip-devops/actions/node/prepare@v1
      env:
        GIT_PRIVATE_KEY: ${{secrets.GIT_PRIVATE_KEY}}

    # ############# Build and test #############

    - name: Build the component
      uses: pip-devops/actions/node/build@v1

    - name: Test the component
      uses: pip-devops/actions/node/test@v1

    ############# Release to dockerhub #############

    - name: Install powershell
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https
        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell


    - name: Release binary artifacts
      run: ./publish.ps1
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}


    ############# Clear #############

    - name: Clean up
      uses: pip-devops/actions/node/clear@v1
